# -*- coding: utf-8 -*-
"""gün5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZJ6jfpjTBnCVMCMDimSCMYn2EN47gFm
"""

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Maths": [85, 70, 95, 60, 88],
    "Science": [90, 80, 85, 70, 95],
    "English": [78, 88, 92, 65, 91]
}
df= pd.DataFrame(data)

df.mean(numeric_only=True)
average= df[['English', 'Maths', 'Science']].mean(axis=1) #tüm sütunlar sayı olmadığı için (name sutunu isim yani object) hepsinin adını yazdık. yoksa df.mean(axis=1) yazacaktık

df['Average']= average
df[df["Name"].isin(["Bob", "David"])]

average2= df.mean(axis=1, numeric_only=True)
df['average2']=average2

df["Average"].idxmax()

df.loc[df["Average"].idxmax()]

avg= df["Average"].mean()
print(f"General Average: {avg:.2f}")

sorted= df.sort_values(by="Average", ascending= False)
sorted
df.loc[df["Average"].idxmin()]
df.loc[df["Maths"].idxmax()]

import matplotlib.pyplot as plt
df.plot(x="Name", y=["Maths","Science","English","Average"], kind="bar")
plt.show()

df.to_csv("student_scores.csv", index=False)

